const cardColors = [
  { name: "steal", color: "#f4f4f4" },
  { name: "ice", color: "#58ABF6" },
  { name: "water", color: "#58ABF6" },
  { name: "electric", color: "#FFCE4B" },
  { name: "grass", color: "#2CDAB1" },
  { name: "fire", color: "#F7786B" },
  { name: "ground", color: "#62302a" },
  { name: "rock", color: "#d5d5d4" },
  { name: "fairy", color: "#fceaff" },
  { name: "poison", color: "#2CDAB1" },
  { name: "bug", color: "#2CDAB1" },
  { name: "dragon", color: "#97b3e6" },
  { name: "dark", color: "#993299" },
  { name: "psychic", color: "#eaeda1" },
  { name: "flying", color: "#f4e7da" },
  { name: "normal", color: "#f4e7da" },
  { name: "ghost", color: "#f4e7da" },
  { name: "fighting", color: "#e6e0d4" },
];
export default cardColors;
